# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: dailysignin

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  dailyrun:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10

    - name: Config git
      run: |
        git config user.email "ww-rm@qq.com"
        git config user.name "ww-rm"
        git pull --ff
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Run dailysignin
      run: |
        python3 -m dailysignin "conf/dailysignin.json" ${{ secrets.RUNKEY }}
    - name: Commit dailysignin
      run: |
        git add .
        bash "scripts/safe_commit.sh" "autorun-dailysignin"
        git pull --ff
        git push
